[package]
name = "example"
version = "0.1.0"
edition = "2021"

[[bench]]
harness = false
name = "i18n_bench"

[dependencies]
ftl-builtin = { path = "../builtin" }
unic-langid = { version = "0.9", features = ["unic-langid-macros"] }

[dev-dependencies]
criterion = "0.8"

[build-dependencies]
ftl-codegen = { path = "../codegen", features = ["builtin"] }
