use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::fs;
use std::path::Path;

use fluent_syntax::ast::{self, Entry, Expression, InlineExpression, PatternElement, VariantKey};
use fluent_syntax::parser;

use crate::ast::*;
use crate::fmt::{gen_fn_decl, generate_one_function};
use crate::params::collect_params;
use crate::util::{sanitize, sanitize_const, sanitize_upper};

pub struct Generator {
    pub primary: String,
    pub locales: BTreeMap<String, Vec<Message>>,
}

impl Generator {
    pub fn load(dir: &Path, primary: &str) -> Self {
        let mut locales = BTreeMap::new();
        for entry in fs::read_dir(dir).expect("Cannot read locales directory") {
            let entry = entry.expect("invalid directory entry");
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("ftl") {
                continue;
            }
            let locale = path
                .file_stem()
                .expect("file has no stem")
                .to_str()
                .expect("filename is not UTF-8")
                .to_string();
            let source = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
            let resource = parser::parse(source.as_str())
                .unwrap_or_else(|e| panic!("Parse error in {}: {:?}", path.display(), e));
            locales.insert(locale, Self::extract(&resource));
        }
        assert!(
            locales.contains_key(primary),
            "Primary locale '{}' not found",
            primary,
        );
        let primary_keys: BTreeSet<&str> =
            locales[primary].iter().map(|m| m.name.as_str()).collect();
        for (name, msgs) in &locales {
            if name == primary {
                continue;
            }
            let locale_keys: BTreeSet<&str> = msgs.iter().map(|m| m.name.as_str()).collect();
            let extra: Vec<&&str> = locale_keys.difference(&primary_keys).collect();
            if !extra.is_empty() {
                panic!("Locale '{}' has extra messages: {:?}", name, extra);
            }
        }
        Generator {
            primary: primary.to_string(),
            locales,
        }
    }

    fn extract(resource: &ast::Resource<&str>) -> Vec<Message> {
        let mut msgs = Vec::new();
        for entry in &resource.body {
            if let Entry::Message(msg) = entry {
                if let Some(pattern) = &msg.value {
                    msgs.push(Message {
                        name: msg.id.name.to_string(),
                        elements: convert_elements(&pattern.elements),
                    });
                }
            }
        }
        msgs
    }

    pub fn generate(&self) -> String {
        let mut out = String::new();
        let locales: Vec<&String> = self.locales.keys().collect();

        writeln!(out, "// Auto-generated by ftl-codegen").unwrap();
        writeln!(out, "// Primary language: {}", self.primary).unwrap();
        writeln!(out, "#[allow(non_upper_case_globals, unused)]").unwrap();
        writeln!(out).unwrap();

        for locale in &locales {
            self.emit_module(locale, &mut out);
        }
        self.emit_trait(&mut out);
        for locale in &locales {
            self.emit_impl(locale, &mut out);
        }
        self.emit_runtime(&locales, &mut out);

        writeln!(out, "#[macro_export]").unwrap();
        writeln!(out, "macro_rules! t {{").unwrap();
        writeln!(
            out,
            "    ($key:ident) => {{ $crate::get_locale().$key() }};"
        )
        .unwrap();
        writeln!(
            out,
            "    ($key:ident($($args:expr),* $(,)?)) => {{ $crate::get_locale().$key($($args),*) }};"
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
        out
    }

    fn emit_module(&self, locale: &str, out: &mut String) {
        let mod_name = sanitize(locale);
        writeln!(out, "pub mod {} {{", mod_name).unwrap();
        writeln!(out, "    use std::fmt::Write;").unwrap();

        let msgs = &self.locales[locale];
        let primary_msgs = &self.locales[&self.primary];
        let locale_keys: BTreeSet<&str> = msgs.iter().map(|m| m.name.as_str()).collect();

        for p_msg in primary_msgs {
            let params = collect_params(&p_msg.elements);
            if locale_keys.contains(p_msg.name.as_str()) {
                let msg = msgs
                    .iter()
                    .find(|m| m.name == p_msg.name)
                    .expect("message missing from locale");
                let code = generate_one_function(&msg.name, &msg.elements, &params, locale);
                writeln!(out, "{}", code.trim_end()).unwrap();
            } else {
                writeln!(
                    out,
                    "{}",
                    generate_one_function(&p_msg.name, &p_msg.elements, &params, &self.primary,)
                        .trim_end()
                )
                .unwrap();
                writeln!(
                    out,
                    "// WARNING: '{}' missing, using '{}' fallback",
                    p_msg.name, locale
                )
                .unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    fn emit_trait(&self, out: &mut String) {
        writeln!(out, "pub trait I18n {{").unwrap();
        for msg in &self.locales[&self.primary] {
            let params = collect_params(&msg.elements);
            writeln!(out, "    fn {};", gen_fn_decl(&msg.name, &params, true)).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    fn emit_impl(&self, locale: &str, out: &mut String) {
        let struct_name = sanitize_upper(locale);
        let mod_name = sanitize(locale);
        writeln!(out, "pub struct {};", struct_name).unwrap();
        writeln!(out, "impl I18n for {} {{", struct_name).unwrap();
        for msg in &self.locales[&self.primary] {
            let params = collect_params(&msg.elements);
            let args = params
                .keys()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "    fn {} {{", gen_fn_decl(&msg.name, &params, true)).unwrap();
            writeln!(out, "        {}::{}({})", mod_name, msg.name, args).unwrap();
            writeln!(out, "    }}").unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "pub const {}: {} = {};",
            sanitize_const(locale),
            struct_name,
            struct_name
        )
        .unwrap();
        writeln!(out).unwrap();
    }

    fn emit_runtime(&self, locales: &[&String], out: &mut String) {
        let primary = sanitize_const(&self.primary);

        writeln!(out, "use std::sync::atomic::{{AtomicU8, Ordering}};").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "static LOCALE_ID: AtomicU8 = AtomicU8::new(0);").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "pub fn get_locale() -> &'static (dyn I18n + Sync) {{").unwrap();
        writeln!(out, "    match LOCALE_ID.load(Ordering::Acquire) {{").unwrap();
        for (idx, locale) in locales.iter().enumerate() {
            if **locale != self.primary {
                writeln!(out, "        {} => &{},", idx, sanitize_const(locale)).unwrap();
            }
        }
        writeln!(out, "        _ => &{},", primary).unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "pub enum Lang {{").unwrap();
        for locale in locales {
            writeln!(out, "    {},", sanitize_upper(locale)).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "pub fn set_lang(lang: Lang) {{").unwrap();
        writeln!(out, "    let id = match lang {{").unwrap();
        for (idx, locale) in locales.iter().enumerate() {
            writeln!(out, "        Lang::{} => {},", sanitize_upper(locale), idx).unwrap();
        }
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    LOCALE_ID.store(id, Ordering::Release);").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

fn convert_elements(elems: &[PatternElement<&str>]) -> Vec<crate::ast::PatternElement> {
    elems.iter().map(|e| convert_element(e)).collect()
}

fn convert_element(e: &PatternElement<&str>) -> crate::ast::PatternElement {
    match e {
        PatternElement::TextElement { value } => {
            crate::ast::PatternElement::Text(value.to_string())
        }
        PatternElement::Placeable { expression } => convert_expression(expression),
    }
}

fn convert_expression(expr: &Expression<&str>) -> crate::ast::PatternElement {
    match expr {
        Expression::Inline(inline) => match inline {
            InlineExpression::VariableReference { id } => {
                crate::ast::PatternElement::VarRef(id.name.to_string())
            }
            other => panic!("Unsupported expression: {:?}", other),
        },
        Expression::Select { selector, variants } => {
            let name = match selector {
                InlineExpression::VariableReference { id } => id.name.to_string(),
                other => panic!("Select selector must be a variable: {:?}", other),
            };
            let vs = variants
                .iter()
                .map(|v| {
                    let key = match &v.key {
                        VariantKey::Identifier { name } => KeyType::Ident(name.to_string()),
                        VariantKey::NumberLiteral { value } => KeyType::Num(value.to_string()),
                    };
                    Variant {
                        key,
                        elements: convert_elements(&v.value.elements),
                        default: v.default,
                    }
                })
                .collect();
            crate::ast::PatternElement::Select {
                selector: name,
                variants: vs,
            }
        }
    }
}
