use std::fs;
use std::path::Path;

fn main() {
    println!("cargo::rustc-check-cfg=cfg(coverage)");
    println!("cargo::rustc-check-cfg=cfg(coverage_nightly)");
    println!("cargo::rerun-if-changed=../cldr/cldr-core/supplemental/plurals.json");

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let json_path = manifest_dir.join("../cldr/cldr-core/supplemental/plurals.json");
    let out_dir_str = std::env::var("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_dir_str);
    let out_path = out_dir.join("plural_gen.rs");

    let json_str = fs::read_to_string(&json_path).expect("Failed to read plurals.json");
    let root: serde_json::Value = serde_json::from_str(&json_str).expect("Invalid plurals.json");

    let mut entries: Vec<(String, Vec<(String, String)>)> = Vec::new();

    let table = root["supplemental"]["plurals-type-cardinal"]
        .as_object()
        .expect("Missing plurals-type-cardinal");

    for (tag, categories) in table {
        let categories = categories.as_object().expect("categories not object");
        let mut out = Vec::new();
        for (key, val) in categories {
            let Some(cat) = key.strip_prefix("pluralRule-count-") else {
                continue;
            };
            if cat == "other" {
                continue;
            }
            let Some(raw) = val.as_str() else {
                continue;
            };
            let Some(rust_expr) = cldr_to_rust(raw) else {
                continue;
            };
            out.push((cat.to_string(), rust_expr));
        }
        if out.is_empty() {
            continue;
        }
        entries.push((tag.clone(), out));
    }

    entries.sort_by_key(|(k, _)| k.clone());

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n\n");
    code.push_str("pub(crate) fn lookup_rules(locale: &str) -> Option<&'static [(&'static str, &'static str)]> {\n");
    code.push_str("    match locale {\n");
    for (tag, rules) in &entries {
        code.push_str(&format!("        {:?} => Some(&{:?}),\n", tag, rules));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    fs::write(&out_path, code).expect("Failed to write plural_gen.rs");
}

const OR_SEP: &str = " or ";
const AND_SEP: &str = " and ";
const RANGE_SEP: &str = "..";

fn cldr_to_rust(raw: &str) -> Option<String> {
    let rule = raw.split('@').next()?.trim();
    if rule.is_empty() {
        return None;
    }

    let mut or_terms = rule.split(OR_SEP).peekable();
    let mut out = Vec::new();

    while let Some(or_part) = or_terms.next() {
        match compile_or_part(or_part) {
            Some(expr) => out.push(expr),
            None => return None,
        }
    }

    if out.is_empty() {
        return None;
    }
    Some(out.join(" || "))
}

fn compile_or_part(s: &str) -> Option<String> {
    let mut and_terms = s.split(AND_SEP).peekable();
    let mut out = Vec::new();

    while let Some(rel) = and_terms.next() {
        let rel = rel.trim();
        if rel.is_empty() {
            continue;
        }
        if is_trivial(rel) {
            continue;
        }
        if uses_unsupported_var(rel) {
            return None;
        }

        let expanded = expand_relation(rel);
        if expanded.len() == 1 {
            out.push(expanded.into_iter().next().unwrap());
        } else {
            out.push(expanded.join(" || "));
        }
    }

    if out.is_empty() {
        return None;
    }
    let joined = out.join(" && ");
    Some(if and_terms.peek().is_some() {
        format!("({})", joined)
    } else {
        joined
    })
}

fn is_trivial(rel: &str) -> bool {
    let rel = rel.trim();
    rel == "v = 0" || rel == "w = 0" || rel == "f = 0" || rel == "t = 0"
}

fn uses_unsupported_var(rel: &str) -> bool {
    for var in &['v', 'w', 'f', 't', 'c', 'e'] {
        if is_standalone_var(rel, *var) {
            return true;
        }
    }
    false
}

fn is_standalone_var(s: &str, var: char) -> bool {
    let bytes = s.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] != var as u8 {
            continue;
        }
        let left_ok = i == 0 || bytes[i - 1] == b' ' || bytes[i - 1] == b'(';
        let right_ok = i + 1 >= bytes.len()
            || bytes[i + 1] == b' '
            || bytes[i + 1] == b'='
            || bytes[i + 1] == b'.'
            || bytes[i + 1] == b')';
        if left_ok && right_ok {
            return true;
        }
    }
    false
}

fn expand_relation(rel: &str) -> Vec<String> {
    let rel = normalize_var(rel);
    let (expr, op, values) = match parse_relation(&rel) {
        Some(t) => t,
        None => return vec![rel],
    };

    if !values.contains(',') {
        return vec![emit_value(expr, op, values)];
    }

    if op == "!=" {
        let parts: Vec<String> = values
            .split(',')
            .map(|v| {
                let v = v.trim();
                if v.is_empty() {
                    return String::new();
                }
                emit_value(expr, op, v)
            })
            .filter(|s| !s.is_empty())
            .collect();
        return vec![parts.join(" && ")];
    }

    values
        .split(',')
        .map(|v| {
            let v = v.trim();
            if v.is_empty() {
                return String::new();
            }
            emit_value(expr, op, v)
        })
        .filter(|s| !s.is_empty())
        .collect()
}

fn normalize_var(s: &str) -> String {
    let s = s.replace(" i ", " n ");
    if let Some(rest) = s.strip_prefix("i ") {
        format!("n {}", rest)
    } else if s == "i" {
        "n".to_string()
    } else {
        s
    }
}

fn parse_relation(rel: &str) -> Option<(&str, &str, &str)> {
    const CLDR_NEQ: &str = " !=";
    const CLDR_EQ: &str = " =";
    if let Some(pos) = rel.find(CLDR_NEQ) {
        let (left, right) = rel.split_at(pos);
        Some((left.trim(), "!=", right[CLDR_NEQ.len()..].trim()))
    } else if let Some(pos) = rel.find(CLDR_EQ) {
        let (left, right) = rel.split_at(pos);
        Some((left.trim(), "==", right[CLDR_EQ.len()..].trim()))
    } else {
        None
    }
}

fn emit_value(expr: &str, op: &str, value: &str) -> String {
    if let Some((lo, hi)) = value.split_once(RANGE_SEP) {
        let lo = lo.trim();
        let hi = hi.trim();
        if op == "!=" {
            format!("!({} >= {} && {} <= {})", expr, lo, expr, hi)
        } else {
            format!("{} >= {} && {} <= {}", expr, lo, expr, hi)
        }
    } else {
        format!("{} {} {}", expr, op, value)
    }
}
