[package]
name = "ftl-codegen"
version = "0.1.0"
edition = "2021"
description = "Compile-time Fluent (.ftl) translation to type-safe Rust functions"
repository = "https://github.com/MC-XiaoHei/ftl"
license = "MIT"

[dependencies]
fluent-syntax = "0.12"
indoc = "2.0"
unic-langid = "0.9"

[build-dependencies]
serde_json = "1.0"

