use serde_json::Value;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo::rustc-check-cfg=cfg(coverage)");

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let cldr_main = manifest_dir.join("../cldr/cldr-numbers-full/main");
    let out_dir_str = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir_str).join("cldr_generated.rs");

    println!("cargo::rerun-if-changed=../cldr/cldr-numbers-full/main");

    let mut dirs: Vec<String> = Vec::new();
    for entry in fs::read_dir(&cldr_main).unwrap() {
        let entry = entry.unwrap();
        if entry.file_type().unwrap().is_dir() {
            if let Ok(name) = entry.file_name().into_string() {
                if !name.starts_with('.') {
                    dirs.push(name);
                }
            }
        }
    }
    dirs.sort();

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n\n");
    emit_structs(&mut code);
    emit_currency_arrays(&mut code, &dirs, &cldr_main);
    emit_all_locales(&mut code, &dirs, &cldr_main);
    emit_lookup_fn(&mut code);

    fs::write(&out_path, code).unwrap();
}

fn emit_structs(code: &mut String) {
    code.push_str(
        "pub struct CurrencyEntry {\n\
         pub symbol: &'static str,\n\
         pub name: &'static str,\n\
         }\n\n",
    );
    code.push_str(
        "pub struct LocaleData {\n\
         pub locale: &'static str,\n\
         pub currency_format: &'static str,\n\
         pub percent_format: &'static str,\n\
         pub currencies: &'static [(&'static str, CurrencyEntry)],\n\
         }\n\n",
    );
}

fn emit_currency_arrays(code: &mut String, dirs: &[String], cldr_main: &Path) {
    for locale in dirs {
        let arr_name = ident(locale);
        let path = cldr_main.join(locale).join("currencies.json");
        let json: Value = serde_json::from_str(&fs::read_to_string(&path).unwrap()).unwrap();

        let pointer = format!("/main/{}/numbers/currencies", pointer_key(locale));
        let mut pairs: Vec<(String, String, String)> = Vec::new();
        if let Some(map) = json.pointer(&pointer).and_then(|v| v.as_object()) {
            for (cc, info) in map {
                let symbol = match info.get("symbol").and_then(|s| s.as_str()) {
                    Some(s) if !s.is_empty() => s.to_string(),
                    _ => continue,
                };
                let name = info
                    .get("displayName")
                    .and_then(|s| s.as_str())
                    .unwrap_or("")
                    .to_string();
                pairs.push((cc.clone(), symbol, name));
            }
        }
        pairs.sort_by_key(|(c, _, _)| c.clone());

        code.push_str(&format!(
            "static {}: &[(&str, CurrencyEntry)] = &[\n",
            arr_name
        ));
        for (cc, sym, name) in &pairs {
            code.push_str(&format!(
                "    (\"{}\", CurrencyEntry {{ symbol: \"{}\", name: \"{}\" }}),\n",
                esc(cc),
                esc(sym),
                esc(name),
            ));
        }
        code.push_str("];\n\n");
    }
}

fn emit_all_locales(code: &mut String, dirs: &[String], cldr_main: &Path) {
    code.push_str("pub(crate) static ALL_LOCALES: &[LocaleData] = &[\n");
    for locale in dirs {
        let arr_name = ident(locale);
        let cf = extract_format(
            cldr_main,
            locale,
            "currencyFormats-numberSystem-latn",
            "¤#,##0.00",
        );
        let pf = extract_format(
            cldr_main,
            locale,
            "percentFormats-numberSystem-latn",
            "#,##0%",
        );
        code.push_str(&format!(
            "    LocaleData {{ locale: \"{}\", currency_format: \"{}\", \
             percent_format: \"{}\", currencies: {} }},\n",
            esc(locale),
            esc(&cf),
            esc(&pf),
            arr_name,
        ));
    }
    code.push_str("];\n\n");
}

fn emit_lookup_fn(code: &mut String) {
    code.push_str(
        "pub(crate) fn lookup(locale: &str) -> Option<&'static LocaleData> {\n\
         ALL_LOCALES.binary_search_by_key(&locale, |d| d.locale)\n\
         .ok().map(|i| &ALL_LOCALES[i])\n\
         }\n",
    );
}

fn extract_format(cldr_main: &Path, locale: &str, key: &str, fallback: &str) -> String {
    let path = cldr_main.join(locale).join("numbers.json");
    let content = match fs::read_to_string(&path) {
        Ok(c) => c,
        Err(_) => return fallback.to_string(),
    };
    let json: Value = match serde_json::from_str(&content) {
        Ok(j) => j,
        Err(_) => return fallback.to_string(),
    };
    let pointer = format!("/main/{}/numbers", pointer_key(locale));
    json.pointer(&pointer)
        .and_then(|n| n.get(key))
        .and_then(|f| f.get("standard"))
        .and_then(|s| s.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| fallback.to_string())
}

fn ident(s: &str) -> String {
    if s.is_empty() {
        return "C_EMPTY".to_string();
    }
    let mut out = String::with_capacity(s.len() + 4);
    out.push_str("C_");
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    out
}

fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

fn pointer_key(s: &str) -> String {
    s.replace('~', "~0").replace('/', "~1")
}
