[package]
name = "ftl-builtin"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed_decimal = { version = "0.7", features = ["ryu"] }
icu_calendar = { version = "2", default-features = false, features = ["compiled_data"] }
icu_datetime = { version = "2", default-features = false, features = ["compiled_data"] }
icu_decimal = { version = "2", default-features = false, features = ["compiled_data"] }
icu_locale_core = "2"
icu_time = { version = "2", default-features = false, features = ["compiled_data"] }
unic-langid = "0.9"
writeable = "0.6"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
